# swagger.yaml
openapi: 3.0.0
info:
  title: Payment SDK API
  description: API for processing payments and managing payment methods.
  version: 1.0.0

servers:
  - url: http://localhost:4242
    description: Local development server

paths:
  /api/create-payment-intent:
    post:
      summary: Creates a Stripe Payment Intent
      description: This endpoint initiates a payment on Stripe and returns a clientSecret that the frontend can use to complete the payment.
      tags:
        - Payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  description: The amount to be charged, in the smallest currency unit (e.g., cents for USD).
                  example: 2000 # This would be $20.00
              required:
                - amount
      responses:
        '200':
          description: Payment Intent created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  clientSecret:
                    type: string
                    description: The client secret of the Payment Intent.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: A description of the error.